Revert "REFPLTB-2361 : Fetch error -> use SRCPV in PV for OE."
This reverts commit d69865301619217e614aa0af2b3799f3b9983bcd.

Reason for revert: Causing BRCM fetch failures:
bb.data_smart.ExpansionError: Failure expanding variable SRCPV, expression was ${@bb.fetch2.get_srcrev(d)} which triggered exception FetchError: Fetcher failure: SRCREV was used yet no valid SCM was found in SRC_URI

ERROR: Task (virtual:multilib:lib32:/home/jenkins/jenkinsroot/workspace/build-brcm-refapp/EXEC_0/meta-cmf/recipes-core/dbus/gdbus-client/gdbus-client_git.bb:do_fetch) failed with exit code '1'

Probably brcmexternalsrc definitions also need updating.

Change-Id: I841865460be860344184eaff4c22626c6e0b6927